application: helloworld
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: helloGAE.php

- url: /Form
  script: Form.php

- url: /Static
  script: StaticFile.php

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets